service: kotone
runtime: python37
instance_class: F2
includes:
  - .env.yaml

handlers:
  - url: /favicon\.ico
    static_files: view/build/favicon.ico
    upload: view/build/favicon.ico

  - url: /static
    static_dir: view/build/static

  - url: /
    static_files: view/build/index.html
    upload: view/build/index.html

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto